/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{html,ts}'],
  theme: {
    extend: {
      colors: {
        background: 'var(--mh-bg)',
        'on-background': 'var(--mh-text-primary)',
        surface: 'var(--mh-surface)',
        'surface-dim': 'var(--mh-surface-dim)',
        'surface-bright': 'var(--mh-surface-bright)',
        'surface-container-lowest': 'var(--mh-surface-container-lowest)',
        'surface-container-low': 'var(--mh-surface-container-low)',
        'surface-container': 'var(--mh-surface-container)',
        'surface-container-high': 'var(--mh-surface-container-high)',
        'surface-container-highest': 'var(--mh-surface-container-highest)',
        'on-surface': 'var(--mh-text-primary)',
        'on-surface-variant': 'var(--mh-text-secondary)',
        primary: 'var(--mh-brand)',
        'on-primary': 'var(--mh-on-primary)',
        'primary-container': 'var(--mh-primary-container)',
        'on-primary-container': 'var(--mh-on-primary-container)',
        secondary: 'var(--mh-accent)',
        'on-secondary': '#ffffff',
        outline: 'var(--mh-border)',
        'outline-variant': 'var(--mh-border-strong)',
        error: 'var(--mh-error)',
      },
      fontFamily: {
        sans: ['Plus Jakarta Sans', 'Inter', 'sans-serif'],
        inter: ['Plus Jakarta Sans', 'Inter', 'sans-serif'],
        h1: ['Plus Jakarta Sans', 'Inter', 'sans-serif'],
        h2: ['Plus Jakarta Sans', 'Inter', 'sans-serif'],
        h3: ['Plus Jakarta Sans', 'Inter', 'sans-serif'],
        'body-lg': ['Plus Jakarta Sans', 'Inter', 'sans-serif'],
        'body-md': ['Plus Jakarta Sans', 'Inter', 'sans-serif'],
        'body-sm': ['Plus Jakarta Sans', 'Inter', 'sans-serif'],
        'label-md': ['Plus Jakarta Sans', 'Inter', 'sans-serif'],
        'label-sm': ['Plus Jakarta Sans', 'Inter', 'sans-serif'],
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        '2xl': '48px',
        '3xl': '64px',
        gutter: '24px',
      },
    },
  },
  plugins: [],
};
