# Generated by Django 5.2.13 on 2026-06-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_average_rating_product_review_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='is_verified_purchase',
            field=models.BooleanField(default=True),
        ),
    ]
